import sys
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
from scipy.stats import ks_2samp

import argparse

parser = argparse.ArgumentParser(description="This script generates a csv with many per gene data for downstream analyses and plots")
parser.add_argument("-n", "--name", default="", help="A string for the title of the plot")
parser.add_argument("-c", '--csv', required=True, help="csv file generated by csv_landscape.py, with detailed per gene data for a single species")

args = parser.parse_args()

df = pd.read_csv(args.csv)
df = df.query("core_acc != 'other'")
thefile = open(args.csv)

print (df)

fig = plt.figure(figsize=(18, 8))
fig.suptitle(args.name, fontsize=16)
gs = fig.add_gridspec(ncols=3, nrows=4)
acc = df.query("core_acc == 'acc'")
core = df.query("core_acc == 'core'")

scafngenes = {}
for i in df.scaffold:
	scafngenes[i] = [len(df.query("scaffold == '"+i+"'")),len(core.query("scaffold == '"+i+"'")),len(acc.query("scaffold == '"+i+"'"))]
ngenes = {"scaffold":[], "totalngenes":[], "accngenes":[], "corengenes":[]}

for i in scafngenes:
	ngenes["scaffold"].append(i)
	ngenes["totalngenes"].append(scafngenes[i][0])
	ngenes["corengenes"].append(scafngenes[i][1])
	ngenes["accngenes"].append(scafngenes[i][2])
ngenes = pd.DataFrame(ngenes)

sns.set(style="whitegrid")


############
ax1 = fig.add_subplot(gs[2,:-1], xlim=[0.4,0.6])
sns.kdeplot(hue="core_acc", x="gc5kb", data=df, palette="Set1", fill=True,  bw_adjust=0.1)
plt.ylabel("GC% in 5Kb\naround gene", size=10)
plt.xticks(fontsize=8)
plt.yticks(ticks=[])
gc1kb_a = df[df['core_acc'] == 'acc']['gc5kb']
gc1kb_b = df[df['core_acc'] == 'core']['gc5kb']

ax1_ks_unequal, ax1_csameasa_pval = ks_2samp(gc1kb_a, gc1kb_b, alternative="two-sided")
ax1_ks_cgreaterthana, ax1_cgreaterthana_pval = ks_2samp(gc1kb_a, gc1kb_b, alternative="greater")
ax1_ks_clessthana, ax1_clessthana_pval = ks_2samp(gc1kb_a, gc1kb_b, alternative="less")
x1, y1 = 0.6, max(ax1.get_ylim())
minx1 = min(ax1.get_xlim())
lenx1 = x1 - minx1

ax1.text(x=x1-0.3*lenx1, y=0.25*y1, s="Core > Acc", color="black", fontsize=10)
ax1.text(x=x1-0.3*lenx1, y=0.35*y1, s="Core < Acc", color="black", fontsize=10)
ax1.text(x=x1-0.3*lenx1, y=0.45*y1, s="Core = Acc", color="black", fontsize=10)
ax1.add_patch(plt.Rectangle(xy=(x1-0.31*lenx1, 0.2*y1), width=0.17*lenx1, height=0.4*y1, color="lightgrey"))

c1eq, c1greater, c1less = "white", "white", "white"
if ax1_csameasa_pval < 0.05: c1eq = "black"
if ax1_cgreaterthana_pval < 0.05: c1greater = "black"
if ax1_clessthana_pval < 0.05: c1less = "black"

ax1.add_patch(plt.Rectangle(xy=(x1-0.2*lenx1, 0.27*y1), width=0.04*lenx1, height=0.04*y1, color=c1less))
ax1.add_patch(plt.Rectangle(xy=(x1-0.2*lenx1, 0.37*y1), width=0.04*lenx1, height=0.04*y1, color=c1greater))
ax1.add_patch(plt.Rectangle(xy=(x1-0.2*lenx1, 0.47*y1), width=0.04*lenx1, height=0.04*y1, color=c1eq))

############
ax2 = fig.add_subplot(gs[3,:-1])
sns.kdeplot(hue="core_acc", x="exon_p", data=df, palette="Set1", fill=True,  bw_adjust=0.1)
plt.xticks(fontsize=8)
plt.yticks(ticks=[])
plt.ylabel("Percent of\nexonic sequence", size=10)
plt.tick_params(axis='y', which='both', bottom=False, top=False, labelbottom=False)
plt.tick_params(axis='x', which='both', direction="in")
exonic_a = df[df['core_acc'] == 'acc']['exon_p']
exonic_b = df[df['core_acc'] == 'core']['exon_p']

ax2_ks_unequal, ax2_csameasa_pval = ks_2samp(exonic_a, exonic_b, alternative="two-sided")
ax2_ks_cgreaterthana, ax2_cgreaterthana_pval = ks_2samp(exonic_a, exonic_b, alternative="greater")
ax2_ks_clessthana, ax2_clessthana_pval = ks_2samp(exonic_a, exonic_b, alternative="less")
x2, y2 = max(ax2.get_xlim()), max(ax2.get_ylim())

ax2.text(x=x2-0.3*x2, y=0.25*y2, s="Core > Acc", color="black", fontsize=10)
ax2.text(x=x2-0.3*x2, y=0.35*y2, s="Core < Acc", color="black", fontsize=10)
ax2.text(x=x2-0.3*x2, y=0.45*y2, s="Core = Acc", color="black", fontsize=10)
ax2.add_patch(plt.Rectangle(xy=(x2-0.31*x2, 0.2*y2), width=0.17*x2, height=0.4*y2, color="lightgrey"))

c2eq, c2greater, c2less = "white", "white", "white"
if ax2_csameasa_pval < 0.05: c2eq = "black"
if ax2_cgreaterthana_pval < 0.05: c2greater = "black"
if ax2_clessthana_pval < 0.05: c2less = "black"

ax2.add_patch(plt.Rectangle(xy=(x2-0.2*x2, 0.27*y2), width=0.04*x2, height=0.04*y2, color=c2less))
ax2.add_patch(plt.Rectangle(xy=(x2-0.2*x2, 0.37*y2), width=0.04*x2, height=0.04*y2, color=c2greater))
ax2.add_patch(plt.Rectangle(xy=(x2-0.2*x2, 0.47*y2), width=0.04*x2, height=0.04*y2, color=c2eq))


############
ax3 = fig.add_subplot(gs[:,2], xlim=[0,30])
x1, x2, y1, y2 = [], [], [], []
for n in range(max(df.num_exons)):
	x1.append(n-0.2)
	x2.append(n+0.2)
	y1.append((len(core.query("num_exons == "+str(n)))/len(core)*100))
	y2.append((len(acc.query("num_exons == "+str(n)))/len(acc)*100))
#plt.bar(x1, y1, width=0.5, label="Core")
#plt.bar(x2, y2, width=0.5, label="Acc", color="Crimson")
sns.histplot(hue="core_acc", x="num_exons", data=df, palette="Set1", fill=True, binwidth=1, element="poly")
plt.ylabel("Number of exons", size=10)
plt.xticks(fontsize=8)
plt.yticks(ticks=[])
num_exons_a = df[df['core_acc'] == 'acc']['num_exons']
num_exons_b = df[df['core_acc'] == 'core']['num_exons']
ax3_ks_unequal, ax3_csameasa_pval = ks_2samp(num_exons_a, num_exons_b, alternative="two-sided")
ax3_ks_cgreaterthana, ax3_cgreaterthana_pval = ks_2samp(num_exons_a, num_exons_b, alternative="greater")
ax3_ks_clessthana, ax3_clessthana_pval = ks_2samp(num_exons_a, num_exons_b, alternative="less")
x3, y3 = max(ax3.get_xlim()), max(ax3.get_ylim())

ax3.text(x=x3-0.28*x3, y=0.23*y3, s="Core > Acc", color="black", fontsize=10)
ax3.text(x=x3-0.28*x3, y=0.28*y3, s="Core < Acc", color="black", fontsize=10)
ax3.text(x=x3-0.28*x3, y=0.33*y3, s="Core = Acc", color="black", fontsize=10)
ax3.add_patch(plt.Rectangle(xy=(x3-0.31*x3, 0.2*y3), width=0.3*x3, height=0.18*y3, color="lightgrey"))

c3eq, c3greater, c3less = "white", "white", "white"
if ax3_csameasa_pval < 0.05: c3eq = "black"
if ax3_cgreaterthana_pval < 0.05: c3greater = "black"
if ax3_clessthana_pval < 0.05: c3less = "black"

ax3.add_patch(plt.Rectangle(xy=(x3-0.07*x3, 0.22*y3), width=0.04*x3, height=0.04*y3, color=c3less))
ax3.add_patch(plt.Rectangle(xy=(x3-0.07*x3, 0.27*y3), width=0.04*x3, height=0.04*y3, color=c3greater))
ax3.add_patch(plt.Rectangle(xy=(x3-0.07*x3, 0.32*y3), width=0.04*x3, height=0.04*y3, color=c3eq))

############
ax4 = fig.add_subplot(gs[0,:-1], xlim=[0,2500])
f4 = sns.histplot(hue="core_acc", x="n_dist", data=df, palette="Set1", fill=True, binwidth=10, element="poly")
plt.yticks(ticks=[])
plt.ylabel("Distance to\nnearest gene", size=10)
plt.xticks(fontsize=8)
n_dist_a = df[df['core_acc'] == 'acc']['n_dist']
n_dist_b = df[df['core_acc'] == 'core']['n_dist']
x4, y4 = max(ax4.get_xlim()), max(ax4.get_ylim())

ax4_ks_unequal, ax4_csameasa_pval = ks_2samp(n_dist_a, n_dist_b, alternative="two-sided")
ax4_ks_cgreaterthana, ax4_cgreaterthana_pval = ks_2samp(n_dist_a, n_dist_b, alternative="greater")
ax4_ks_clessthana, ax4_clessthana_pval = ks_2samp(n_dist_a, n_dist_b, alternative="less")
x4, y4 = max(ax4.get_xlim()), max(ax4.get_ylim())

ax4.text(x=x4-0.3*x4, y=0.25*y4, s="Core > Acc", color="black", fontsize=10)
ax4.text(x=x4-0.3*x4, y=0.35*y4, s="Core < Acc", color="black", fontsize=10)
ax4.text(x=x4-0.3*x4, y=0.45*y4, s="Core = Acc", color="black", fontsize=10)
ax4.add_patch(plt.Rectangle(xy=(x4-0.31*x4, 0.2*y4), width=0.17*x4, height=0.4*y4, color="lightgrey"))

c4eq, c4greater, c4less = "white", "white", "white"
if ax4_csameasa_pval < 0.05: c4eq = "black"
if ax4_cgreaterthana_pval < 0.05: c4greater = "black"
if ax4_clessthana_pval < 0.05: c4less = "black"

ax4.add_patch(plt.Rectangle(xy=(x4-0.2*x4, 0.27*y4), width=0.04*x4, height=0.04*y4, color=c4less))
ax4.add_patch(plt.Rectangle(xy=(x4-0.2*x4, 0.37*y4), width=0.04*x4, height=0.04*y4, color=c4greater))
ax4.add_patch(plt.Rectangle(xy=(x4-0.2*x4, 0.47*y4), width=0.04*x4, height=0.04*y4, color=c4eq))

############
ax5 = fig.add_subplot(gs[1,:-1], xlim=[0,20000])
sns.kdeplot(hue="core_acc", x="len", data=df, palette="Set1", fill=True,  bw_adjust=0.1)
plt.ylabel("Gene length", size=10)
plt.xticks(fontsize=8)
len_a = df[df['core_acc'] == 'acc']['len']
len_b = df[df['core_acc'] == 'core']['len']
ax5_ks_statistic, ax5_p_value = ks_2samp(len_a, len_b)
plt.yticks(ticks=[])
plt.tick_params(axis='x', which='both', direction="in")
x5, y5 = max(ax5.get_xlim()), max(ax5.get_ylim())

ax5_ks_unequal, ax5_csameasa_pval = ks_2samp(len_a, len_b, alternative="two-sided")
ax5_ks_cgreaterthana, ax5_cgreaterthana_pval = ks_2samp(len_a, len_b, alternative="greater")
ax5_ks_clessthana, ax5_clessthana_pval = ks_2samp(len_a, len_b, alternative="less")

ax5.text(x=x5-0.3*x5, y=0.25*y5, s="Core > Acc", color="black", fontsize=10)
ax5.text(x=x5-0.3*x5, y=0.35*y5, s="Core < Acc", color="black", fontsize=10)
ax5.text(x=x5-0.3*x5, y=0.45*y5, s="Core = Acc", color="black", fontsize=10)
ax5.add_patch(plt.Rectangle(xy=(x5-0.31*x5, 0.2*y5), width=0.17*x5, height=0.4*y5, color="lightgrey"))

c5eq, c5greater, c5less = "white", "white", "white"
if ax5_csameasa_pval < 0.05: c5eq = "black"
if ax5_cgreaterthana_pval < 0.05: c5greater = "black"
if ax5_clessthana_pval < 0.05: c5less = "black"

ax5.add_patch(plt.Rectangle(xy=(x5-0.2*x5, 0.27*y5), width=0.04*x5, height=0.04*y5, color=c5less))
ax5.add_patch(plt.Rectangle(xy=(x5-0.2*x5, 0.37*y5), width=0.04*x5, height=0.04*y5, color=c5greater))
ax5.add_patch(plt.Rectangle(xy=(x5-0.2*x5, 0.47*y5), width=0.04*x5, height=0.04*y5, color=c5eq))

plt.show()
